### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by linwenjun** [sunyanan891114/homework4#1]
用鼠标粘贴进去的关键词，没有处理

**Comment by linwenjun** [comment]
js文件不能放到stylesheets文件夹下

**Comment by linwenjun** [comment]
https://github.com/sunyanan891114/homework4/blob/gh-pages/stylesheets/search.js#L11
这里为什么要处理"key word"

**Comment by linwenjun** [comment]
所有缩进要改成4个空格或者2个空格，而不要用tab键

**Comment by sunyanan891114** [comment]
已修改，
input设置了初始默认值keywords ，如果当前input值为默认值，就把里面内容情况，因此在Js文件中，对 key word进行了处理
